export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const EXPAND_MENU = 'EXPAND_MENU'

export const SWITCH_EFFECT = 'SWITCH_EFFECT'


//以下是SSO数据管理方法
export const SET_SYS_USERLIST= 'SET_SYS_USERUSERLIST'

export const SET_SYS_CURRENTUSER= 'SET_SYS_CURRENTUSER'

export const SET_SYS_ROLELIST= 'SET_SYS_ROLELIST'

export const SET_SYS_APPSRCLIST= 'SET_SYS_APPSRCLIST'

export const SET_SYS_DEPARTMENT= 'SET_SYS_DEPARTMENT'

export const SET_SYS_CONFIG= 'SET_SYS_CONFIG'

export const SET_SYS_LOGS= 'SET_SYS_LOGS'

