export const TOGGLE_DEVICE = 'TOGGLE_DEVICE';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const EXPAND_MENU = 'EXPAND_MENU';

export const SWITCH_EFFECT = 'SWITCH_EFFECT';


//以下是SSO数据管理方法
export const SET_SYS_MESSAGESHOW = 'SET_SYS_MESSAGESHOW';

export const SET_SYS_MESSAGETYPE = 'SET_SYS_MESSAGETYPE';

export const SET_SYS_USERLIST = 'SET_SYS_USERUSERLIST';

export const SET_SYS_CURRENTUSER = 'SET_SYS_CURRENTUSER';

export const SET_SYS_USERROLEINFO = 'SET_SYS_USERROLEINFO';

export const SET_SYS_USERDEPARTMENTINFO = 'SET_SYS_USERDEPARTMENTINFO';

export const SET_SYS_ROLELIST = 'SET_SYS_ROLELIST';

export const SET_SYS_CURRENTROLE = 'SET_SYS_CURRENTROLE';

export const SET_SYS_APPSRCLIST = 'SET_SYS_APPSRCLIST';

export const SET_SYS_DEPARTMENTLIST = 'SET_SYS_DEPARTMENTLIST';

export const SET_SYS_CURRENTDEPARTMENT = 'SET_SYS_CURRENTDEPARTMENT';

export const SET_SYS_POWERLIST = 'SET_SYS_POWERLIST';

export const SET_SYS_CURRENTPOWER = 'SET_SYS_CURRENTPOWER';

export const SET_SYS_OPERATS = 'SET_SYS_OPERATS';

export const SET_SYS_SYSTEMLIST = 'SET_SYS_SYSTEMLIST';

export const SET_SYS_LOGLIST = 'SET_SYS_LOGLIST';

export const SET_SYS_REQUESTLIST = 'SET_SYS_REQUESTLIST';

export const SET_SYS_CUSTOMERLIST = 'SET_SYS_CUSTOMERLIST';

