export const TOGGLE_DEVICE = 'TOGGLE_DEVICE';

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

export const EXPAND_MENU = 'EXPAND_MENU';

export const SWITCH_EFFECT = 'SWITCH_EFFECT';


//以下是校区数据管理方法
export const SET_MESSAGESHOW = 'SET_MESSAGESHOW';

export const SET_MESSAGETYPE = 'SET_MESSAGETYPE';

export const SET_PERMISSION = 'SET_PERMISSION';

export const SET_MENU = 'SET_MENU';

export const SET_ZONELIST = 'SET_ZONELIST';

export const SET_CURRENTZONE = 'SET_CURRENTZONE';

export const SET_CURRENTZONEINFO = 'SET_CURRENTZONEINFO';

export const SET_BUILDINGTYPELIST = 'SET_BUILDINGTYPELIST';

export const SET_CURRENTTYPE = 'SET_CURRENTTYPE';

export const SET_BUILDINGLIST = 'SET_BUILDINGLIST';

export const SET_CURRENTBUILDING = 'SET_CURRENTBUILDING';

export const SET_SERVICETYPELIST = 'SET_SERVICETYPELIST';

export const SET_CURRENTSERVICETYPE = 'SET_CURRENTSERVICETYPE';

export const SET_SERVICEINFOLIST = 'SET_SERVICEINFOLIST';

export const SET_CURRENTSERVICEINFO = 'SET_CURRENTSERVICEINFO';

export const SET_INFORMATIONLIST = 'SET_INFORMATIONLIST';

export const SET_CURRENTINFORMATION = 'SET_CURRENTINFORMATION';

export const SET_GUIDELIST = 'SET_GUIDELIST';

export const SET_CURRENTGUIDE = 'SET_CURRENTGUIDE';

export const SET_PARTYLIST = 'SET_PARTYLIST';

export const SET_CURRENTPARTY = 'SET_CURRENTPARTY';

export const SET_ORGANIZATIONLIST = 'SET_ORGANIZATIONLIST';

export const SET_CURRENTORGANIZATION = 'SET_CURRENTORGANIZATION';

export const SET_AGENCYGROUPLIST = 'SET_AGENCYGROUPLIST';

export const SET_CURRENTAGENCYGROUP = 'SET_CURRENTAGENCYGROUP';

export const SET_LINKZONELIST = 'SET_LINKZONELIST';

export const SET_UNLINKZONELIST = 'SET_UNLINKZONELIST';

export const SET_LINKINFOLIST = 'SET_LINKINFOLIST';

export const SET_UNLINKINFOLIST = 'SET_UNLINKINFOLIST';

export const SET_LINKGUIDELIST = 'SET_LINKGUIDELIST';

export const SET_UNLINKGUIDELIST = 'SET_UNLINKGUIDELIST';

export const SET_AGENCYLIST = 'SET_AGENCYLIST';

export const SET_CURRENTAGENCY = 'SET_CURRENTAGENCY';



